name: CI
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
  push:
    branches: 
      - master

jobs:
  tests:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Set up git repository
        uses: actions/checkout@v2
      - name: Install zsh
        if: runner.os == 'Linux'
        run: sudo apt-get upgrade; sudo apt-get install zsh -y
      - name: Test installing
        run: bash ./tools/install.sh
      - name: Check string
        run: zsh -n ./spyrhoo.zsh-theme
